[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20" # Specify Node.js LTS version
  # You can specify a Node.js version here if your project requires it
  # Example: NODE_VERSION = "18"
  # For now, we'll leave it commented out unless a specific version is known to be needed.

# This rule is important for Single Page Applications (SPAs) like Vite + React Router.
# It ensures that all paths are served by index.html, allowing client-side routing to handle them.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
