// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yredqbagzyyylutriqbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyZWRxYmFnenl5eWx1dHJpcWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDUzMDMsImV4cCI6MjA2MjgyMTMwM30.lBidqwYiS_dAkPGK0uA5bWfwUCmVNlaiesC_iLSHeXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);